name: TypeScript SDK Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSIONING_POLICY: manual
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
      - run: npm install -g npm@latest
      - name: Publish to npm
        run: |
          if npm view "@scalar/galaxy-sdk@0.1.1" version >/dev/null 2>&1; then
            echo "@scalar/galaxy-sdk@0.1.1 already published to npm, skipping"
          else
            npm publish --provenance --access public
          fi
